; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [platformio]
; src_dir = .

[common]
lib_deps_external =
  ; links2004/WebSockets
  ; links2004/WebSockets@^2.5.2
  adafruit/Adafruit SH110X @ ^2.1.8
  adafruit/Adafruit GFX Library @ ^1.11.5
  olikraus/U8g2 @ ^2.35.15
  robocre8/EPMC_I2C_Client@^1.1.0
  robocre8/EIMU_I2C_Client@^1.1.0
  https://github.com/pololu/vl53l0x-arduino.git
  https://github.com/JChristensen/movingAvg.git
  madhephaestus/ESP32Servo@^1.1.9
  https://github.com/samuko-things/Ultrasonic.git
  https://github.com/meirarc/Led.git
  https://github.com/meirarc/Button.git

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1

framework = arduino
monitor_speed = 115200

lib_deps = ${common.lib_deps_external}
